### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### Julia-i18n/julia-i18n now has a Chat Room on Gitter

@Ismael-VC has just created a chat room. You can visit it here: [https://gitter.im/Julia-i18n/julia-i18n](https://gitter.im/Julia-i18n/julia-i18n?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/Julia-i18n/julia-i18n?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by Ismael-VC** [comment]
⚠️⚠️⚠️ **In case anyone sees this pull request, before the chat room is announced to the public, please do not post anything, until it is announced publicly so that the messages in the old chat room can be transferred over to this new one, and continuity is not lost, thanks!** ⚠️⚠️⚠️

**Comment by ChrisRackauckas** [comment]
> :warning::warning::warning: In case anyone sees this pull request, before the chat room is announced to the public, please do not post anything, until it is announced publicly so that the messages in the old chat room can be transferred over to this new one, and continuity is not lost, thanks! :warning::warning::warning:

That's one way of handling it :smile_cat:

**Comment by Ismael-VC** [comment]
@waldyrious do we have any update from the Gitter team about the transfer of the old logs?

**Comment by waldyrious** [comment]
Not yet, @Ismael-VC, but it took them a few days to respond the last time around. I suspect they have limited HR, so I'm not too concerned yet. @MadLittleMods has been very helpful so far, so I'm confident :) I'll update this thread as soon as I get a response.

**Comment by waldyrious** [comment]
And it's done!! 🎉 🎉 🎉

**Pull request closed without merging**
